apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-k8s
spec:
  selector:
    matchLabels:
      run: hello-k8s
  replicas: 1
  template:
    metadata:
      labels:
        run: hello-k8s
    spec:
      containers:
      - name: hello-k8s
        image: 894711206975.dkr.ecr.us-east-2.amazonaws.com/favorite_movies:20102022_1155
        ports:
        - containerPort: 3331
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
---
apiVersion: v1
kind: Service
metadata:
  name: hello-k8s
  labels:
    run: hello-k8s
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3331
  selector:
    run: hello-k8s
  type: LoadBalancer